name : run-unit-tests

on: push

jobs:

  build:
  
    # we can specific the OS to run tests on
    runs-on: ubuntu-latest
    
    # a job is a sequence of steps
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        
    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requiremens.txt
        
    - name: Test with pytest
      run: |
        python3 -m pytest -v tests/test_factorial.py
